### ISSUE TITLE
Presenters are leaking if do FragmentManager.popBackStack()

### ISSUE THREAD

**Issue by ar-g** [grandcentrix/ThirtyInch#83] opened 2017-04-17 09:25 UTC
First of all thank you for a library we are using it for all our presenters and fragments, around 50. 

Recently we came across very strange behavior we have an activity with a chain of 10 fragments and when user reach the last one we are doing
```java
getSupportFragmentManager().popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE)
``` 
then we create a different fragment. All these fragments are related to one scope which we keep inside activity and after the user leaves activity component is destroyed.

What we noticed that after one such scenario we are leaking 10 presenters. And if the user does it a couple of times we will have 20 leaked presenters.

Moreover, we investigated and found that we are using `popBackStack` very actively throughout our app, that mean we have many presenters which are leaking. 

How can we fix it?

**Comment by StefMa** [comment] 2017-04-17 10:42
Hi,

this is a duplicate of #33 and #68.
We are already working on that on #78.
Thank you for the repot. But because we know that issue and we have already some issues for that I will close it...

**Closed by StefMa** 2017-04-17 10:42 UTC

**Comment by ar-g** [comment] 2017-04-17 11:32
@StefMa Do you know when the fix will be available? And how can we help to make it happen faster?

**Comment by StefMa** [comment] 2017-04-18 10:11
At this time we have to deadline for fixing this bug.
But sine we have the same trouble with our internal projects we are looking forward to fix that as soon as possible.

However. You can help by reviewing (and maybe collaborate) on #78!
