### ISSUE TITLE
Presenter is being killed most of the time

### ISSUE THREAD

**Issue by k0shk0sh** [grandcentrix/ThirtyInch#74] opened 2017-03-08 16:31 UTC
Hello Pascal,  I have a problem and I need to understand what could cause it, so basically I started FastHub with version rc2 & then I noticed that you have updated the lib, since I like to be updated about everything I did actually update to __rc3__ however I noticed that whenever the activity goes in background for awhile not to long _a minute or less_ the data is being saved in the presenter are lost which cause the app to somehow lose an important flag or an id. I couldn't really know what is going until i reverted back to __rc2__ and everything seems to work fine except now the data will live for a bit longer than the __rc3__ .  I know it seem confusing but I couldn't really explained more than that. 
Could you let me know what could cause this? is it a memory problem maybe with my phone or there is something I'm doing wrong. 
> fyi: I'm using the default configuration which mean I didn't touch the presenter nor the view configuration. 

Thank you in advance & I hope to see the library continue it's awesome work.

**Comment by vRallev** [comment] 2017-03-08 17:10
Did the process die when the app was in background? That would be my guess.

**Comment by k0shk0sh** [comment] 2017-03-08 17:15
@vRallev I'm not really sure tho, the activities in backstack remains but of course losing their data as well which causes me to re-init the whole activities again. basically it would look like this 
Activity A > B > C.
on app resume, C presenter lost it's data. press back B lost its data, press back to A, A as well lost its data. 

Its weird tbh. I don't think we have this issue if we use the stable version which one of the company I'm working at has it on the production app and everything seems to be working fine.

**Comment by vRallev** [comment] 2017-03-08 17:20
Maybe there's a difference between those version, but I didn't catch something important.

You can reproduce the behavior easily if you press home and kill the app process (this can be done from the IDE) and then reopen the app from the recent list. We had the same issue, that's why I created #50 and #51. This fixed this issue for us.

**Comment by k0shk0sh** [comment] 2017-03-08 17:26
I might be cloning your fork and give it a shot I had love to see it in ThirtyInch tbh. I can't really tell why it's not merged but I'm sure @passsy has his own thought on this.
thanks for your help.

**Comment by passsy** [comment] 2017-03-09 10:26
Thanks for the report. It would be helpful when you enable the logging for `Ti` (`TiLog.setLogger(TiLog.LOGCAT);`). So we can see what exactly happens to the presenters.

I checked the [diff](https://github.com/grandcentrix/ThirtyInch/compare/v0.8.0-rc2...v0.8.0-rc3) between `rc2` and `rc3` but didn't notice changes when saving or recovering the presenter. Are you using Activity Presenters only? Because Fragments where refactored (hopefully without problems).

Since FastHub is open source I'd like to debug the problem there myself. Can you tell me where exactly your Presenters get lost?

You already have a `BasePresenter` and adding support for `onSaveInstanceState` can be added with a few lines of code (especially when using reflection). That's why #50 isn't merged, yet.

**Comment by k0shk0sh** [comment] 2017-03-09 11:11
Hello . @passsy , Thanks for your reply, the losing of state mostly happens in [RepoPagerView](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/ui/modules/repos/RepoPagerView.java) and anywhere else tho. 

I'll be waiting for your feedback on this.
Thank you  again Pascal.

**Comment by passsy** [comment] 2017-03-09 16:02
We fixed the bug together here is the resulting PR: https://github.com/k0shk0sh/FastHub/pull/116

The Activity was "initializing" the presenter differently based on `saveInstanceState` being `null` or not with the data from `getIntent()`. The correct way is to pass the intent data in `providePresenter`.

The Activity now starts after process death like it would start initially and the problems are gone.

**Closed by passsy** 2017-03-09 16:02 UTC
